// Provenance TP — AI-generated code fingerprint markers.
// Generated by Copilot / ChatGPT — do not review carefully
public class AiGeneratedFingerprint {
  public int Add(int a, int b) => a + b; // AI-authored stub
}
